const sampleProducts = [
  {
    id: 1,
    name: "Laptop",
    category: "Electronics",
    price: 999,
    inStock: true,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Mouse",
    category: "Electronics",
    price: 25,
    inStock: true,
    rating: 4.2,
  },
  {
    id: 3,
    name: "Keyboard",
    category: "Electronics",
    price: 75,
    inStock: false,
    rating: 3.7,
  },
  {
    id: 4,
    name: "Monitor",
    category: "Electronics",
    price: 299,
    inStock: true,
    rating: 4.4,
  },
  {
    id: 5,
    name: "Desk Chair",
    category: "Furniture",
    price: 199,
    inStock: true,
    rating: 4.3,
  },
  {
    id: 6,
    name: "Desk",
    category: "Furniture",
    price: 399,
    inStock: false,
    rating: 4.6,
  },
  {
    id: 7,
    name: "Lamp",
    category: "Furniture",
    price: 49,
    inStock: true,
    rating: 4.1,
  },
  {
    id: 8,
    name: "Notebook",
    category: "Stationery",
    price: 5,
    inStock: true,
    rating: 4.0,
  },
  {
    id: 9,
    name: "Pen Set",
    category: "Stationery",
    price: 15,
    inStock: true,
    rating: 4.5,
  },
  {
    id: 10,
    name: "Headphones",
    category: "Electronics",
    price: 149,
    inStock: true,
    rating: 4.8,
  },
  {
    id: 11,
    name: "Webcam",
    category: "Electronics",
    price: 89,
    inStock: true,
    rating: 4.3,
  },
  {
    id: 12,
    name: "USB Cable",
    category: "Electronics",
    price: 12,
    inStock: true,
    rating: 4.0,
  },
  {
    id: 13,
    name: "Bookshelf",
    category: "Furniture",
    price: 159,
    inStock: false,
    rating: 4.5,
  },
  {
    id: 14,
    name: "Office Chair Mat",
    category: "Furniture",
    price: 45,
    inStock: true,
    rating: 4.2,
  },
  {
    id: 15,
    name: "Stapler",
    category: "Stationery",
    price: 8,
    inStock: true,
    rating: 4.1,
  },
  {
    id: 16,
    name: "Sticky Notes",
    category: "Stationery",
    price: 6,
    inStock: true,
    rating: 4.4,
  },
  {
    id: 17,
    name: "Tablet",
    category: "Electronics",
    price: 499,
    inStock: true,
    rating: 4.6,
  },
  {
    id: 18,
    name: "Desk Organizer",
    category: "Stationery",
    price: 22,
    inStock: false,
    rating: 4.3,
  },
  {
    id: 19,
    name: "Standing Desk",
    category: "Furniture",
    price: 599,
    inStock: true,
    rating: 4.7,
  },
  {
    id: 20,
    name: "Wireless Charger",
    category: "Electronics",
    price: 35,
    inStock: true,
    rating: 4.4,
  },
  {
    id: 21,
    name: "Coffee Maker",
    category: "Appliances",
    price: 79,
    inStock: true,
    rating: 4.5,
  },
  {
    id: 22,
    name: "Microwave",
    category: "Appliances",
    price: 129,
    inStock: true,
    rating: 4.3,
  },
  {
    id: 23,
    name: "Blender",
    category: "Appliances",
    price: 59,
    inStock: false,
    rating: 4.2,
  },
  {
    id: 24,
    name: "Toaster",
    category: "Appliances",
    price: 39,
    inStock: true,
    rating: 4.1,
  },
  {
    id: 25,
    name: "Running Shoes",
    category: "Sports",
    price: 89,
    inStock: true,
    rating: 4.6,
  },
  {
    id: 26,
    name: "Yoga Mat",
    category: "Sports",
    price: 29,
    inStock: true,
    rating: 4.4,
  },
  {
    id: 27,
    name: "Dumbbells Set",
    category: "Sports",
    price: 119,
    inStock: false,
    rating: 4.7,
  },
  {
    id: 28,
    name: "Water Bottle",
    category: "Sports",
    price: 18,
    inStock: true,
    rating: 4.3,
  },
  {
    id: 29,
    name: "Backpack",
    category: "Accessories",
    price: 49,
    inStock: true,
    rating: 4.5,
  },
  {
    id: 30,
    name: "Sunglasses",
    category: "Accessories",
    price: 69,
    inStock: true,
    rating: 4.2,
  },
];

export default sampleProducts;
