const sampleProducts = [
  {
    id: 1,
    name: "Laptop",
    category: "Electronics",
    price: 999,
    inStock: true,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Mouse",
    category: "Electronics",
    price: 25,
    inStock: true,
    rating: 4.2,
  },
  {
    id: 3,
    name: "Keyboard",
    category: "Electronics",
    price: 75,
    inStock: false,
    rating: 4.7,
  },
  {
    id: 4,
    name: "Monitor",
    category: "Electronics",
    price: 299,
    inStock: true,
    rating: 4.4,
  },
  {
    id: 5,
    name: "Desk Chair",
    category: "Furniture",
    price: 199,
    inStock: true,
    rating: 4.3,
  },
  {
    id: 6,
    name: "Desk",
    category: "Furniture",
    price: 399,
    inStock: false,
    rating: 4.6,
  },
  {
    id: 7,
    name: "Lamp",
    category: "Furniture",
    price: 49,
    inStock: true,
    rating: 4.1,
  },
  {
    id: 8,
    name: "Notebook",
    category: "Stationery",
    price: 5,
    inStock: true,
    rating: 4.0,
  },
  {
    id: 9,
    name: "Pen Set",
    category: "Stationery",
    price: 15,
    inStock: true,
    rating: 4.5,
  },
  {
    id: 10,
    name: "Headphones",
    category: "Electronics",
    price: 149,
    inStock: true,
    rating: 4.8,
  },
];

export default sampleProducts;
