export default {
  categories: [
    { id: "all", label: "All" },
    { id: "electronics", label: "Electronics" },
    { id: "sports", label: "Sports" },
    { id: "home", label: "Home" },
    { id: "accessories", label: "Accessories" },
  ],
  products: [
    // Electronics
    {
      id: 1,
      name: "Wireless Headphones",
      category: "electronics",
      price: 79.99,
      image: "🎧",
      rating: 4.5,
      reviews: 128,
      stock: 2,
    },
    {
      id: 2,
      name: "Smart Watch",
      category: "electronics",
      price: 199.99,
      image: "⌚",
      rating: 4.8,
      reviews: 256,
      stock: 2,
    },
    {
      id: 8,
      name: "Bluetooth Speaker",
      category: "electronics",
      price: 59.99,
      image: "🔊",
      rating: 4.6,
      reviews: 203,
      stock: 2,
    },
    {
      id: 9,
      name: "Laptop",
      category: "electronics",
      price: 1299.99,
      image: "💻",
      rating: 4.7,
      reviews: 412,
      stock: 3,
    },
    {
      id: 10,
      name: "Smartphone",
      category: "electronics",
      price: 899.99,
      image: "📱",
      rating: 4.6,
      reviews: 523,
      stock: 5,
    },
    {
      id: 11,
      name: "Tablet",
      category: "electronics",
      price: 499.99,
      image: "📱",
      rating: 4.4,
      reviews: 287,
      stock: 4,
    },
    {
      id: 12,
      name: "Wireless Mouse",
      category: "electronics",
      price: 29.99,
      image: "🖱️",
      rating: 4.3,
      reviews: 156,
      stock: 8,
    },
    {
      id: 13,
      name: "Keyboard",
      category: "electronics",
      price: 89.99,
      image: "⌨️",
      rating: 4.5,
      reviews: 198,
      stock: 6,
    },
    {
      id: 14,
      name: "Webcam",
      category: "electronics",
      price: 69.99,
      image: "📷",
      rating: 4.2,
      reviews: 134,
      stock: 4,
    },
    {
      id: 15,
      name: "USB Hub",
      category: "electronics",
      price: 24.99,
      image: "🔌",
      rating: 4.1,
      reviews: 89,
      stock: 10,
    },

    // Sports
    {
      id: 3,
      name: "Running Shoes",
      category: "sports",
      price: 89.99,
      image: "👟",
      rating: 4.6,
      reviews: 189,
      stock: 2,
    },
    {
      id: 6,
      name: "Yoga Mat",
      category: "sports",
      price: 29.99,
      image: "🧘",
      rating: 4.4,
      reviews: 167,
      stock: 2,
    },
    {
      id: 16,
      name: "Dumbbell Set",
      category: "sports",
      price: 149.99,
      image: "🏋️",
      rating: 4.7,
      reviews: 234,
      stock: 3,
    },
    {
      id: 17,
      name: "Tennis Racket",
      category: "sports",
      price: 119.99,
      image: "🎾",
      rating: 4.5,
      reviews: 145,
      stock: 4,
    },
    {
      id: 18,
      name: "Basketball",
      category: "sports",
      price: 34.99,
      image: "🏀",
      rating: 4.6,
      reviews: 178,
      stock: 6,
    },
    {
      id: 19,
      name: "Soccer Ball",
      category: "sports",
      price: 29.99,
      image: "⚽",
      rating: 4.5,
      reviews: 201,
      stock: 7,
    },
    {
      id: 20,
      name: "Bicycle",
      category: "sports",
      price: 599.99,
      image: "🚴",
      rating: 4.8,
      reviews: 312,
      stock: 2,
    },
    {
      id: 21,
      name: "Swimming Goggles",
      category: "sports",
      price: 19.99,
      image: "🥽",
      rating: 4.3,
      reviews: 123,
      stock: 8,
    },
    {
      id: 22,
      name: "Jump Rope",
      category: "sports",
      price: 12.99,
      image: "🪢",
      rating: 4.2,
      reviews: 98,
      stock: 12,
    },
    {
      id: 23,
      name: "Resistance Bands",
      category: "sports",
      price: 24.99,
      image: "💪",
      rating: 4.4,
      reviews: 167,
      stock: 9,
    },

    // Home
    {
      id: 5,
      name: "Coffee Maker",
      category: "home",
      price: 129.99,
      image: "☕",
      rating: 4.7,
      reviews: 312,
      stock: 2,
    },
    {
      id: 7,
      name: "Desk Lamp",
      category: "home",
      price: 39.99,
      image: "💡",
      rating: 4.2,
      reviews: 78,
      stock: 2,
    },
    {
      id: 24,
      name: "Blender",
      category: "home",
      price: 79.99,
      image: "🥤",
      rating: 4.5,
      reviews: 234,
      stock: 4,
    },
    {
      id: 25,
      name: "Vacuum Cleaner",
      category: "home",
      price: 249.99,
      image: "🧹",
      rating: 4.6,
      reviews: 289,
      stock: 3,
    },
    {
      id: 26,
      name: "Air Purifier",
      category: "home",
      price: 179.99,
      image: "💨",
      rating: 4.7,
      reviews: 345,
      stock: 2,
    },
    {
      id: 27,
      name: "Toaster",
      category: "home",
      price: 49.99,
      image: "🍞",
      rating: 4.3,
      reviews: 156,
      stock: 5,
    },
    {
      id: 28,
      name: "Microwave",
      category: "home",
      price: 159.99,
      image: "📻",
      rating: 4.5,
      reviews: 267,
      stock: 3,
    },
    {
      id: 29,
      name: "Electric Kettle",
      category: "home",
      price: 34.99,
      image: "🫖",
      rating: 4.4,
      reviews: 198,
      stock: 6,
    },
    {
      id: 30,
      name: "Humidifier",
      category: "home",
      price: 69.99,
      image: "💧",
      rating: 4.6,
      reviews: 223,
      stock: 4,
    },
    {
      id: 31,
      name: "Fan",
      category: "home",
      price: 44.99,
      image: "🌀",
      rating: 4.2,
      reviews: 134,
      stock: 5,
    },

    // Accessories
    {
      id: 4,
      name: "Backpack",
      category: "accessories",
      price: 49.99,
      image: "🎒",
      rating: 4.3,
      reviews: 95,
      stock: 3,
    },
    {
      id: 32,
      name: "Sunglasses",
      category: "accessories",
      price: 89.99,
      image: "🕶️",
      rating: 4.5,
      reviews: 178,
      stock: 6,
    },
    {
      id: 33,
      name: "Watch",
      category: "accessories",
      price: 149.99,
      image: "⌚",
      rating: 4.6,
      reviews: 234,
      stock: 4,
    },
    {
      id: 34,
      name: "Wallet",
      category: "accessories",
      price: 39.99,
      image: "👛",
      rating: 4.4,
      reviews: 145,
      stock: 8,
    },
    {
      id: 35,
      name: "Belt",
      category: "accessories",
      price: 29.99,
      image: "👔",
      rating: 4.2,
      reviews: 112,
      stock: 10,
    },
    {
      id: 36,
      name: "Hat",
      category: "accessories",
      price: 24.99,
      image: "🧢",
      rating: 4.3,
      reviews: 98,
      stock: 12,
    },
    {
      id: 37,
      name: "Scarf",
      category: "accessories",
      price: 34.99,
      image: "🧣",
      rating: 4.4,
      reviews: 123,
      stock: 7,
    },
    {
      id: 38,
      name: "Gloves",
      category: "accessories",
      price: 19.99,
      image: "🧤",
      rating: 4.1,
      reviews: 87,
      stock: 9,
    },
    {
      id: 39,
      name: "Umbrella",
      category: "accessories",
      price: 22.99,
      image: "☂️",
      rating: 4.3,
      reviews: 156,
      stock: 6,
    },
    {
      id: 40,
      name: "Handbag",
      category: "accessories",
      price: 79.99,
      image: "👜",
      rating: 4.5,
      reviews: 201,
      stock: 4,
    },
  ],
};
