export default {
  products: [
    {
      id: 1,
      name: "Wireless Headphones",
      category: "Electronics",
      price: 79.99,
      image: "🎧",
      rating: 4.5,
      reviews: 128,
      stock: 2,
    },
    {
      id: 2,
      name: "Smart Watch",
      category: "Electronics",
      price: 199.99,
      image: "⌚",
      rating: 4.8,
      reviews: 256,
      stock: 2,
    },
    {
      id: 3,
      name: "Running Shoes",
      category: "Sports",
      price: 89.99,
      image: "👟",
      rating: 4.6,
      reviews: 189,
      stock: 2,
    },
    {
      id: 4,
      name: "Backpack",
      category: "Accessories",
      price: 49.99,
      image: "🎒",
      rating: 4.3,
      reviews: 95,
      stock: 3,
    },
    {
      id: 5,
      name: "Coffee Maker",
      category: "Home",
      price: 129.99,
      image: "☕",
      rating: 4.7,
      reviews: 312,
      stock: 2,
    },
    {
      id: 6,
      name: "Yoga Mat",
      category: "Sports",
      price: 29.99,
      image: "🧘",
      rating: 4.4,
      reviews: 167,
      stock: 2,
    },
    {
      id: 7,
      name: "Desk Lamp",
      category: "Home",
      price: 39.99,
      image: "💡",
      rating: 4.2,
      reviews: 78,
      stock: 2,
    },
    {
      id: 8,
      name: "Bluetooth Speaker",
      category: "Electronics",
      price: 59.99,
      image: "🔊",
      rating: 4.6,
      reviews: 203,
      stock: 2,
    },
    {
      id: 9,
      name: "Bluetooth Speaker2",
      category: "Electronics",
      price: 79.99,
      image: "🔊",
      rating: 3.6,
      reviews: 103,
      stock: 2,
    },
  ],
};
